name: stepper_mobx
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
