name: Publish to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /stepper_mobx/
